name: excali-prod

services:
  excali-api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: apps/http-backend/Dockerfile
    ports:
      - "8001:8000"
    env_file:
      - ./.env
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1GB
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - excali-network

  excali-ws:
    restart: unless-stopped
    build:
      context: .
      dockerfile: apps/ws-backend/Dockerfile
    ports:
      - "9001:9000"
    env_file:
      - ./.env
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512MB
    networks:
      - excali-network

networks:
  excali-network:
    name: excali-network
