export const HTTP_BACKEND = "http://localhost:8000"
export const WS_URL = "ws://localhost:9000"
export const JWT_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRoZWVyYWpAZ21haWwuY29tIiwiaWQiOiI5ZDA3ZjYyZS1hOGQyLTQ2Y2YtYmEyNS1hMzAwZGI5ZWU3YzUiLCJpYXQiOjE3Nzk5MzY0NjksImV4cCI6MTc4MTE0NjA2OSwiYXVkIjoiVXNlciIsImlzcyI6IlNoYXJlZENhbnZhcyJ9.fqjLLhfZGTQl_bQAIqI6N7q_hj9hvNxDjdyVsga7hgQ"